//! SQL Keywords
//!
//! Defines all SQL keywords recognized by the parser.

/// SQL keywords
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Keyword {
    // Query keywords
    Select,
    From,
    Where,
    Group,
    Having,
    Qualify,  // DuckDB: filter on window functions
    Order,
    By,
    Limit,
    Offset,
    Distinct,
    All,

    // Join keywords
    Join,
    Inner,
    Left,
    Right,
    Full,
    Outer,
    Cross,
    On,
    Using,
    Lateral,
    Asof,
    Positional,
    Semi,
    Anti,

    // Set operations
    Union,
    Intersect,
    Except,
    Minus,

    // DDL keywords
    Create,
    Table,
    View,
    Index,
    Schema,
    Database,
    Drop,
    Alter,
    Add,
    Column,
    Rename,
    Modify,
    Change,
    Macro,
    Sequence,
    Temporary,
    Temp,
    Materialized,
    Force,

    // DML keywords
    Insert,
    Into,
    Values,
    Update,
    Delete,
    Set,
    Replace,
    Truncate,
    Returning,
    Conflict,
    Ignore,
    Merge,
    Upsert,

    // Data types
    Integer,
    Int,
    BigInt,
    SmallInt,
    TinyInt,
    Decimal,
    Numeric,
    Real,
    Double,
    Float,
    Varchar,
    Char,
    Text,
    Blob,
    Boolean,
    Bool,
    Date,
    Time,
    Timestamp,
    DateTime,
    Interval,
    Struct,
    List,
    Map,
    Array,
    // Union keyword for type (already have Union for set operation)
    Enum,

    // Constraints
    Primary,
    Key,
    Foreign,
    References,
    Unique,
    Check,
    Not,
    Null,
    Default,
    AutoIncrement,
    Identity,

    // Boolean operators
    And,
    Or,

    // Comparison operators
    Like,
    ILike,
    Between,
    In,
    Exists,
    Is,
    Any,
    Some,

    // Aggregate functions
    Count,
    Sum,
    Avg,
    Min,
    Max,
    StdDev,
    Variance,

    // Window functions
    Over,
    Partition,
    Window,
    Row,
    Rows,
    Range,
    Groups,
    Unbounded,
    Preceding,
    Following,
    Current,
    RowNumber,
    Rank,
    DenseRank,
    Lag,
    Lead,
    FirstValue,
    LastValue,

    // Subquery keywords
    With,
    Recursive,
    As,
    Case,
    When,
    Then,
    Else,
    End,
    If,
    Coalesce,
    NullIf,

    // Transaction keywords
    Begin,
    Start,
    Transaction,
    Commit,
    Rollback,
    Savepoint,
    Release,

    // Index keywords
    Asc,
    Desc,
    Ascending,
    Descending,

    // Table operations
    Show,
    Describe,
    Explain,
    Plan,

    // Import/Export
    Copy,
    To,
    Export,
    Import,

    // Extensions
    Install,
    Load,

    // Database management
    Attach,
    Detach,
    Pragma,
    Use,

    // Other
    True,
    False,
    Unknown,
    Cast,
    Extract,
    Substring,
    Trim,
    Upper,
    Lower,
    Length,
    Position,
    Concat,

    // PIVOT/UNPIVOT keywords (DuckDB extension)
    Pivot,
    Unpivot,
    For,
    Include,

    // Additional keywords for parsing
    Nulls,
    First,
    Last,
    Next,
    Constraint,
    Read,
    Only,
    Write,
    Serializable,
    Repeatable,
    Committed,
    Chain,
    Analyze,
    Verbose,
    Tables,
    Columns,
    Indexes,
    Variables,
    Databases,
    Schemas,
    Filter,
    Respect,
    Measures,
    Sample,
    Tablesample,
    Exclude,
    Ordinality,
}

impl Keyword {
    /// Get all keywords
    pub fn all() -> &'static [Keyword] {
        &[
            // Query keywords
            Keyword::Select,
            Keyword::From,
            Keyword::Where,
            Keyword::Group,
            Keyword::Having,
            Keyword::Qualify,
            Keyword::Order,
            Keyword::By,
            Keyword::Limit,
            Keyword::Offset,
            Keyword::Distinct,
            Keyword::All,
            // Join keywords
            Keyword::Join,
            Keyword::Inner,
            Keyword::Left,
            Keyword::Right,
            Keyword::Full,
            Keyword::Outer,
            Keyword::Cross,
            Keyword::On,
            Keyword::Using,
            Keyword::Lateral,
            Keyword::Asof,
            Keyword::Positional,
            Keyword::Semi,
            Keyword::Anti,
            // Set operations
            Keyword::Union,
            Keyword::Intersect,
            Keyword::Except,
            Keyword::Minus,
            // DDL keywords
            Keyword::Create,
            Keyword::Table,
            Keyword::View,
            Keyword::Index,
            Keyword::Schema,
            Keyword::Database,
            Keyword::Drop,
            Keyword::Alter,
            Keyword::Add,
            Keyword::Column,
            Keyword::Rename,
            Keyword::Modify,
            Keyword::Change,
            Keyword::Macro,
            Keyword::Sequence,
            Keyword::Temporary,
            Keyword::Temp,
            Keyword::Materialized,
            Keyword::Force,
            // DML keywords
            Keyword::Insert,
            Keyword::Into,
            Keyword::Values,
            Keyword::Update,
            Keyword::Delete,
            Keyword::Set,
            Keyword::Replace,
            Keyword::Truncate,
            Keyword::Returning,
            Keyword::Conflict,
            Keyword::Ignore,
            Keyword::Merge,
            Keyword::Upsert,
            // Data types
            Keyword::Integer,
            Keyword::Int,
            Keyword::BigInt,
            Keyword::SmallInt,
            Keyword::TinyInt,
            Keyword::Decimal,
            Keyword::Numeric,
            Keyword::Real,
            Keyword::Double,
            Keyword::Float,
            Keyword::Varchar,
            Keyword::Char,
            Keyword::Text,
            Keyword::Blob,
            Keyword::Boolean,
            Keyword::Bool,
            Keyword::Date,
            Keyword::Time,
            Keyword::Timestamp,
            Keyword::DateTime,
            Keyword::Interval,
            Keyword::Struct,
            Keyword::List,
            Keyword::Map,
            Keyword::Array,
            Keyword::Enum,
            // Constraints
            Keyword::Primary,
            Keyword::Key,
            Keyword::Foreign,
            Keyword::References,
            Keyword::Unique,
            Keyword::Check,
            Keyword::Not,
            Keyword::Null,
            Keyword::Default,
            Keyword::AutoIncrement,
            Keyword::Identity,
            // Boolean operators
            Keyword::And,
            Keyword::Or,
            // Comparison operators
            Keyword::Like,
            Keyword::ILike,
            Keyword::Between,
            Keyword::In,
            Keyword::Exists,
            Keyword::Is,
            Keyword::Any,
            Keyword::Some,
            // Aggregate functions
            Keyword::Count,
            Keyword::Sum,
            Keyword::Avg,
            Keyword::Min,
            Keyword::Max,
            Keyword::StdDev,
            Keyword::Variance,
            // Window functions
            Keyword::Over,
            Keyword::Partition,
            Keyword::Window,
            Keyword::Row,
            Keyword::Rows,
            Keyword::Range,
            Keyword::Groups,
            Keyword::Unbounded,
            Keyword::Preceding,
            Keyword::Following,
            Keyword::Current,
            Keyword::RowNumber,
            Keyword::Rank,
            Keyword::DenseRank,
            Keyword::Lag,
            Keyword::Lead,
            Keyword::FirstValue,
            Keyword::LastValue,
            // Subquery keywords
            Keyword::With,
            Keyword::Recursive,
            Keyword::As,
            Keyword::Case,
            Keyword::When,
            Keyword::Then,
            Keyword::Else,
            Keyword::End,
            Keyword::If,
            Keyword::Coalesce,
            Keyword::NullIf,
            // Transaction keywords
            Keyword::Begin,
            Keyword::Start,
            Keyword::Transaction,
            Keyword::Commit,
            Keyword::Rollback,
            Keyword::Savepoint,
            Keyword::Release,
            // Index keywords
            Keyword::Asc,
            Keyword::Desc,
            Keyword::Ascending,
            Keyword::Descending,
            // Table operations
            Keyword::Show,
            Keyword::Describe,
            Keyword::Explain,
            Keyword::Plan,
            // Import/Export
            Keyword::Copy,
            Keyword::To,
            Keyword::Export,
            Keyword::Import,
            // Extensions
            Keyword::Install,
            Keyword::Load,
            // Database management
            Keyword::Attach,
            Keyword::Detach,
            Keyword::Pragma,
            Keyword::Use,
            // Other
            Keyword::True,
            Keyword::False,
            Keyword::Unknown,
            Keyword::Cast,
            Keyword::Extract,
            Keyword::Substring,
            Keyword::Trim,
            Keyword::Upper,
            Keyword::Lower,
            Keyword::Length,
            Keyword::Position,
            Keyword::Concat,
            // PIVOT/UNPIVOT keywords
            Keyword::Pivot,
            Keyword::Unpivot,
            Keyword::For,
            Keyword::Include,
            // Additional keywords for parsing
            Keyword::Nulls,
            Keyword::First,
            Keyword::Last,
            Keyword::Next,
            Keyword::Constraint,
            Keyword::Read,
            Keyword::Only,
            Keyword::Write,
            Keyword::Serializable,
            Keyword::Repeatable,
            Keyword::Committed,
            Keyword::Chain,
            Keyword::Analyze,
            Keyword::Verbose,
            Keyword::Tables,
            Keyword::Columns,
            Keyword::Indexes,
            Keyword::Variables,
            Keyword::Databases,
            Keyword::Schemas,
            Keyword::Filter,
            Keyword::Respect,
            Keyword::Measures,
            Keyword::Sample,
            Keyword::Tablesample,
            Keyword::Exclude,
            Keyword::Ordinality,
        ]
    }
}

impl std::fmt::Display for Keyword {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = match self {
            // Query keywords
            Keyword::Select => "SELECT",
            Keyword::From => "FROM",
            Keyword::Where => "WHERE",
            Keyword::Group => "GROUP",
            Keyword::Having => "HAVING",
            Keyword::Qualify => "QUALIFY",
            Keyword::Order => "ORDER",
            Keyword::By => "BY",
            Keyword::Limit => "LIMIT",
            Keyword::Offset => "OFFSET",
            Keyword::Distinct => "DISTINCT",
            Keyword::All => "ALL",

            // Join keywords
            Keyword::Join => "JOIN",
            Keyword::Inner => "INNER",
            Keyword::Left => "LEFT",
            Keyword::Right => "RIGHT",
            Keyword::Full => "FULL",
            Keyword::Outer => "OUTER",
            Keyword::Cross => "CROSS",
            Keyword::On => "ON",
            Keyword::Using => "USING",
            Keyword::Lateral => "LATERAL",
            Keyword::Asof => "ASOF",
            Keyword::Positional => "POSITIONAL",
            Keyword::Semi => "SEMI",
            Keyword::Anti => "ANTI",

            // Set operations
            Keyword::Union => "UNION",
            Keyword::Intersect => "INTERSECT",
            Keyword::Except => "EXCEPT",
            Keyword::Minus => "MINUS",

            // DDL keywords
            Keyword::Create => "CREATE",
            Keyword::Table => "TABLE",
            Keyword::View => "VIEW",
            Keyword::Index => "INDEX",
            Keyword::Schema => "SCHEMA",
            Keyword::Database => "DATABASE",
            Keyword::Drop => "DROP",
            Keyword::Alter => "ALTER",
            Keyword::Add => "ADD",
            Keyword::Column => "COLUMN",
            Keyword::Rename => "RENAME",
            Keyword::Modify => "MODIFY",
            Keyword::Change => "CHANGE",
            Keyword::Macro => "MACRO",
            Keyword::Sequence => "SEQUENCE",
            Keyword::Temporary => "TEMPORARY",
            Keyword::Temp => "TEMP",
            Keyword::Materialized => "MATERIALIZED",
            Keyword::Force => "FORCE",

            // DML keywords
            Keyword::Insert => "INSERT",
            Keyword::Into => "INTO",
            Keyword::Values => "VALUES",
            Keyword::Update => "UPDATE",
            Keyword::Delete => "DELETE",
            Keyword::Set => "SET",
            Keyword::Replace => "REPLACE",
            Keyword::Truncate => "TRUNCATE",
            Keyword::Returning => "RETURNING",
            Keyword::Conflict => "CONFLICT",
            Keyword::Ignore => "IGNORE",
            Keyword::Merge => "MERGE",
            Keyword::Upsert => "UPSERT",

            // Data types
            Keyword::Integer => "INTEGER",
            Keyword::Int => "INT",
            Keyword::BigInt => "BIGINT",
            Keyword::SmallInt => "SMALLINT",
            Keyword::TinyInt => "TINYINT",
            Keyword::Decimal => "DECIMAL",
            Keyword::Numeric => "NUMERIC",
            Keyword::Real => "REAL",
            Keyword::Double => "DOUBLE",
            Keyword::Float => "FLOAT",
            Keyword::Varchar => "VARCHAR",
            Keyword::Char => "CHAR",
            Keyword::Text => "TEXT",
            Keyword::Blob => "BLOB",
            Keyword::Boolean => "BOOLEAN",
            Keyword::Bool => "BOOL",
            Keyword::Date => "DATE",
            Keyword::Time => "TIME",
            Keyword::Timestamp => "TIMESTAMP",
            Keyword::DateTime => "DATETIME",
            Keyword::Interval => "INTERVAL",
            Keyword::Struct => "STRUCT",
            Keyword::List => "LIST",
            Keyword::Map => "MAP",
            Keyword::Array => "ARRAY",
            Keyword::Enum => "ENUM",

            // Constraints
            Keyword::Primary => "PRIMARY",
            Keyword::Key => "KEY",
            Keyword::Foreign => "FOREIGN",
            Keyword::References => "REFERENCES",
            Keyword::Unique => "UNIQUE",
            Keyword::Check => "CHECK",
            Keyword::Not => "NOT",
            Keyword::Null => "NULL",
            Keyword::Default => "DEFAULT",
            Keyword::AutoIncrement => "AUTOINCREMENT",
            Keyword::Identity => "IDENTITY",

            // Boolean operators
            Keyword::And => "AND",
            Keyword::Or => "OR",

            // Comparison operators
            Keyword::Like => "LIKE",
            Keyword::ILike => "ILIKE",
            Keyword::Between => "BETWEEN",
            Keyword::In => "IN",
            Keyword::Exists => "EXISTS",
            Keyword::Is => "IS",
            Keyword::Any => "ANY",
            Keyword::Some => "SOME",

            // Aggregate functions
            Keyword::Count => "COUNT",
            Keyword::Sum => "SUM",
            Keyword::Avg => "AVG",
            Keyword::Min => "MIN",
            Keyword::Max => "MAX",
            Keyword::StdDev => "STDDEV",
            Keyword::Variance => "VARIANCE",

            // Window functions
            Keyword::Over => "OVER",
            Keyword::Partition => "PARTITION",
            Keyword::Window => "WINDOW",
            Keyword::Row => "ROW",
            Keyword::Rows => "ROWS",
            Keyword::Range => "RANGE",
            Keyword::Groups => "GROUPS",
            Keyword::Unbounded => "UNBOUNDED",
            Keyword::Preceding => "PRECEDING",
            Keyword::Following => "FOLLOWING",
            Keyword::Current => "CURRENT",
            Keyword::RowNumber => "ROW_NUMBER",
            Keyword::Rank => "RANK",
            Keyword::DenseRank => "DENSE_RANK",
            Keyword::Lag => "LAG",
            Keyword::Lead => "LEAD",
            Keyword::FirstValue => "FIRST_VALUE",
            Keyword::LastValue => "LAST_VALUE",

            // Subquery keywords
            Keyword::With => "WITH",
            Keyword::Recursive => "RECURSIVE",
            Keyword::As => "AS",
            Keyword::Case => "CASE",
            Keyword::When => "WHEN",
            Keyword::Then => "THEN",
            Keyword::Else => "ELSE",
            Keyword::End => "END",
            Keyword::If => "IF",
            Keyword::Coalesce => "COALESCE",
            Keyword::NullIf => "NULLIF",

            // Transaction keywords
            Keyword::Begin => "BEGIN",
            Keyword::Start => "START",
            Keyword::Transaction => "TRANSACTION",
            Keyword::Commit => "COMMIT",
            Keyword::Rollback => "ROLLBACK",
            Keyword::Savepoint => "SAVEPOINT",
            Keyword::Release => "RELEASE",

            // Index keywords
            Keyword::Asc => "ASC",
            Keyword::Desc => "DESC",
            Keyword::Ascending => "ASCENDING",
            Keyword::Descending => "DESCENDING",

            // Table operations
            Keyword::Show => "SHOW",
            Keyword::Describe => "DESCRIBE",
            Keyword::Explain => "EXPLAIN",
            Keyword::Plan => "PLAN",

            // Import/Export
            Keyword::Copy => "COPY",
            Keyword::To => "TO",
            Keyword::Export => "EXPORT",
            Keyword::Import => "IMPORT",

            // Extensions
            Keyword::Install => "INSTALL",
            Keyword::Load => "LOAD",

            // Database management
            Keyword::Attach => "ATTACH",
            Keyword::Detach => "DETACH",
            Keyword::Pragma => "PRAGMA",
            Keyword::Use => "USE",

            // Other
            Keyword::True => "TRUE",
            Keyword::False => "FALSE",
            Keyword::Unknown => "UNKNOWN",
            Keyword::Cast => "CAST",
            Keyword::Extract => "EXTRACT",
            Keyword::Substring => "SUBSTRING",
            Keyword::Trim => "TRIM",
            Keyword::Upper => "UPPER",
            Keyword::Lower => "LOWER",
            Keyword::Length => "LENGTH",
            Keyword::Position => "POSITION",
            Keyword::Concat => "CONCAT",

            // PIVOT/UNPIVOT keywords
            Keyword::Pivot => "PIVOT",
            Keyword::Unpivot => "UNPIVOT",
            Keyword::For => "FOR",
            Keyword::Include => "INCLUDE",

            // Additional keywords for parsing
            Keyword::Nulls => "NULLS",
            Keyword::First => "FIRST",
            Keyword::Last => "LAST",
            Keyword::Next => "NEXT",
            Keyword::Constraint => "CONSTRAINT",
            Keyword::Read => "READ",
            Keyword::Only => "ONLY",
            Keyword::Write => "WRITE",
            Keyword::Serializable => "SERIALIZABLE",
            Keyword::Repeatable => "REPEATABLE",
            Keyword::Committed => "COMMITTED",
            Keyword::Chain => "CHAIN",
            Keyword::Analyze => "ANALYZE",
            Keyword::Verbose => "VERBOSE",
            Keyword::Tables => "TABLES",
            Keyword::Columns => "COLUMNS",
            Keyword::Indexes => "INDEXES",
            Keyword::Variables => "VARIABLES",
            Keyword::Databases => "DATABASES",
            Keyword::Schemas => "SCHEMAS",
            Keyword::Filter => "FILTER",
            Keyword::Respect => "RESPECT",
            Keyword::Measures => "MEASURES",
            Keyword::Sample => "SAMPLE",
            Keyword::Tablesample => "TABLESAMPLE",
            Keyword::Exclude => "EXCLUDE",
            Keyword::Ordinality => "ORDINALITY",
        };
        write!(f, "{}", s)
    }
}
